name = "Coming Soon"
description = "Simple page with name and a countdown to your website's release date & time"

license = "GNU GPLv3"
licenselink = "https://github.com/rofe33/coming-soon/blob/main/LICENCE"

homepage = "https://github.com/rofe33/coming-soon"
demosite = "https://rofe33.github.io/coming-soon"

tags = ["minimal", "dark", "personal", "countdown"]

authors = [
  {name = "Raphael Tannous", homepage = "https://rofe33.github.io"},
  {name = "Mansoor Barri", homepage = "https://mansoorbarri.com"},
]

min_version = "0.111.3"
