baseURL = "https://rofe33.github.io"
languageCode = 'en-us'
theme = "coming-soon"

disableKinds = ['taxonomy', 'term']

[params]
    title = "rofe33"
    description = ""
    favicon = ""
    message = "COMING SOON!"
    release = "February 14, 2024"
    background = ""

socialIcons = [
    {name = "github", url = "https://github.com/rofe33/"},
    {name = "linkedin", url = "https://www.linkedin.com/in/rofe33/"},
]
